# Generated by Django 4.1.5 on 2023-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loginp',
            field=models.BooleanField(default=False, verbose_name='Girişli Profile'),
        ),
    ]
