# Generated by Django 4.1.5 on 2023-07-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0004_alter_userinfo_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='subscribe',
            field=models.BooleanField(default=False, verbose_name='Abonelik'),
        ),
    ]
